<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * BeneficioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficioRepository extends \Doctrine\ORM\EntityRepository
{
}
