<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * CertificadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificadoRepository extends \Doctrine\ORM\EntityRepository
{
}
