<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * CompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompraRepository extends \Doctrine\ORM\EntityRepository
{
}
