<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * DetalleProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
