<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * LineaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
