<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * LineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaRepository extends \Doctrine\ORM\EntityRepository
{
}
