<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * PagoEmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoEmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
