<?php

namespace Wbc\AdministratorBundle\Repository;

/**
 * TipoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
