certificado_index:
    path:     /
    defaults: { _controller: "WbcAdministratorBundle:Certificado:index" }
    methods:  GET

certificado_show:
    path:     /{id}/show
    defaults: { _controller: "WbcAdministratorBundle:Certificado:show" }
    methods:  GET

certificado_new:
    path:     /new
    defaults: { _controller: "WbcAdministratorBundle:Certificado:new" }
    methods:  [GET, POST]

certificado_edit:
    path:     /{id}/edit
    defaults: { _controller: "WbcAdministratorBundle:Certificado:edit" }
    methods:  [GET, POST]

certificado_delete:
    path:     /{id}/delete
    defaults: { _controller: "WbcAdministratorBundle:Certificado:delete" }
