i18nresource_index:
    path:     /
    defaults: { _controller: "WbcAdministratorBundle:I18NResource:index" }
    methods:  GET

i18nresource_show:
    path:     /{id}/show
    defaults: { _controller: "WbcAdministratorBundle:I18NResource:show" }
    methods:  GET

i18nresource_new:
    path:     /new
    defaults: { _controller: "WbcAdministratorBundle:I18NResource:new" }
    methods:  [GET, POST]

i18nresource_edit:
    path:     /{id}/edit
    defaults: { _controller: "WbcAdministratorBundle:I18NResource:edit" }
    methods:  [GET, POST]

i18nresource_delete:
    path:     /{id}/delete
    defaults: { _controller: "WbcAdministratorBundle:I18NResource:delete" }
