pagoempleado_index:
    path:     /
    defaults: { _controller: "WbcAdministratorBundle:PagoEmpleado:index" }
    methods:  GET

pagoempleado_show:
    path:     /{id}/show
    defaults: { _controller: "WbcAdministratorBundle:PagoEmpleado:show" }
    methods:  GET

pagoempleado_new:
    path:     /new
    defaults: { _controller: "WbcAdministratorBundle:PagoEmpleado:new" }
    methods:  [GET, POST]

pagoempleado_edit:
    path:     /{id}/edit
    defaults: { _controller: "WbcAdministratorBundle:PagoEmpleado:edit" }
    methods:  [GET, POST]

pagoempleado_delete:
    path:     /{id}/delete
    defaults: { _controller: "WbcAdministratorBundle:PagoEmpleado:delete" }
