services:
    app.locale_listener:
            class: Wbc\AdministratorBundle\EventListener\LocaleListener
            arguments: ['%kernel.default_locale%', '@service_container']
            tags:
                - { name: kernel.event_subscriber }

    app.user_locale_listener:
            class: Wbc\AdministratorBundle\EventListener\UserLocaleListener
            arguments: ['@session', "@doctrine.orm.entity_manager"]
            tags:
                - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.form.profile:
            class: Wbc\AdministratorBundle\Form\ProfileFormType
            tags:
                - { name: form.type, alias: app_user_profile }

    base.change.listener:
        class: Wbc\AdministratorBundle\EventListener\ChangesListener
        arguments: [ '@service_container' ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    base.request.response.listener:
        class: Wbc\AdministratorBundle\EventListener\RequestAndResponseListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.response }
            - { name: kernel.event_listener, event: kernel.controller }
            - { name: kernel.event_listener, event: kernel.view }