Wbc\AdministratorBundle\Entity\Factura:
    type: entity
    table: factura
    repositoryClass: Wbc\AdministratorBundle\Repository\FacturaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        total:
            type: decimal
            precision: 10
            scale: '2'
        tipo_operacion:
            type: integer
        descripcion:
            type: string
            length: '500'
            nullable: true
        creacion:
            type: datetime
    manyToOne:
      tipo_pago:
        targetEntity: TipoPago
        inversedBy: factura
        joinColumns:
          tipo_pago_id:
            referencedColumnName: id
            nullable: false
      compra:
        targetEntity: Compra
        inversedBy: factura
        joinColumns:
          compra_id:
            referencedColumnName: id
            nullable: true
      venta:
        targetEntity: Venta
        inversedBy: factura
        joinColumns:
          venta_id:
            referencedColumnName: id
            nullable: true
    lifecycleCallbacks: {  }
