Wbc\AdministratorBundle\Entity\Timezone:
  type: entity
  table: base_timezone
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
      nullable: true
    utc_offset:
      type: string
      length: 25
      nullable: true
    php_name:
      type: string
      length: 100
      nullable: true
  oneToMany:
    user:
      targetEntity: Wbc\AdministratorBundle\Entity\User
      mappedBy: locale
